platform :ios, '13.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "Pods target name: " + target.name
    target.build_configurations.each do |config|

      # suppress warnings
      # see https://discord.com/channels/603595811204366337/828973466534936637/1192028592255799317
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'

      # see https://github.com/NativeScript/NativeScript/issues/10034
      if config.build_settings['WRAPPER_EXTENSION'] == 'bundle'
        config.build_settings['DEVELOPMENT_TEAM'] = 'C424ZH53NJ'
      end

      # see https://github.com/NativeScript/NativeScript/issues/8860
      # see https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'

      # see https://stackoverflow.com/questions/63607158/xcode-building-for-ios-simulator-but-linking-in-an-object-file-built-for-ios-f/63714000#63714000
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"

      # see https://github.com/CocoaPods/CocoaPods/issues/12012
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }

      if target.name == 'Realm'
        create_symlink_phase = target.shell_script_build_phases.find { |x| x.name == 'Create Symlinks to Header Folders' }
        create_symlink_phase.always_out_of_date = "1"
        puts "target.name = Realm found"
      end
  
      if target.name.start_with? "GoogleDataTransport"
        target.build_configurations.each do |config|
          config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO' 
        end
      end

    end
  end
end